// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8cFZzF_cFV8FFlQUMiNbUjGRIeDBIYs',
    appId: '1:141913459369:web:a1a7d898c49bdab14337b8',
    messagingSenderId: '141913459369',
    projectId: 'chat-app-4-e54a4',
    authDomain: 'chat-app-4-e54a4.firebaseapp.com',
    storageBucket: 'chat-app-4-e54a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOeguIEUZ98mz4j_4ZeK5yY8C31XNiOc',
    appId: '1:141913459369:android:253823410fced6074337b8',
    messagingSenderId: '141913459369',
    projectId: 'chat-app-4-e54a4',
    storageBucket: 'chat-app-4-e54a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ5VddyLGCWevESMrWcMsjtGejFlRoBLQ',
    appId: '1:141913459369:ios:e531424c6752ce334337b8',
    messagingSenderId: '141913459369',
    projectId: 'chat-app-4-e54a4',
    storageBucket: 'chat-app-4-e54a4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ5VddyLGCWevESMrWcMsjtGejFlRoBLQ',
    appId: '1:141913459369:ios:e531424c6752ce334337b8',
    messagingSenderId: '141913459369',
    projectId: 'chat-app-4-e54a4',
    storageBucket: 'chat-app-4-e54a4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8cFZzF_cFV8FFlQUMiNbUjGRIeDBIYs',
    appId: '1:141913459369:web:9a91f37f911198e54337b8',
    messagingSenderId: '141913459369',
    projectId: 'chat-app-4-e54a4',
    authDomain: 'chat-app-4-e54a4.firebaseapp.com',
    storageBucket: 'chat-app-4-e54a4.appspot.com',
  );

}